table backlog

	column Team_ID
		dataType: string
		summarizeBy: none
		sourceColumn: Team_ID

	column backlog_days
		dataType: double
		summarizeBy: sum
		sourceColumn: backlog_days

	measure 'Days of queued work (backlog)' = SUM ( 'backlog'[backlog_days] )
		formatString: #,0.00
		displayFolder: Measures
		/// Days of queued work for the 'Backlog days of work' visual.

	partition backlog = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\backlog.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"Team_ID", type text},
				        {"backlog_days", type number}
				    })
				in
				    Typed
