table segment

	column segment
		dataType: string
		summarizeBy: none
		sourceColumn: segment

	column cases
		dataType: int64
		summarizeBy: sum
		sourceColumn: cases

	column sla_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: sla_pct

	measure 'SLA compliance % (segment)' = AVERAGE ( 'segment'[sla_pct] )
		formatString: #,0.00
		displayFolder: Measures
		/// SLA compliance % for the 'Segment equity — a null finding, reported anyway' visual.

	partition segment = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExtractFolder & "\segment.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"segment", type text},
				        {"cases", Int64.Type},
				        {"sla_pct", type number}
				    })
				in
				    Typed
